### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by rokity** [sashas777/magento2-customer-attribute-extension#2]
Hi... I want to add this attribute to frontend. I mean when New Customer wants to create an account , I want that the custom attribute it's here with the fields like First Name, Last Name , passwrod ...
How can I do this?

**Comment by sashas777** [comment]
Hi,

You may try to change line 83: 
https://github.com/sashas777/magento2-customer-attribute-extension/blob/master/app/code/Sashas/CustomerAttribute/Setup/InstallData.php#L83

to something like frontend_customer.
