### ISSUE TITLE
disable Sashas_CustomerAttribute module

### ISSUE THREAD

**Issue by johanDev19** [sashas777/magento2-customer-attribute-extension#3]
hi,
how can i delete or disable this module? cuz i disabled this module but i still having magento customer input in muy admin_customer side. i think that it should be a uninstall.php file into setup folder... can you help me with that ? thanks

**Comment by tapahbl4** [comment]
@johanDev19 
```bash
php bin/magento module:disable Sashas_CustomerAttribute
php bin/magento setup:upgrade
php bin/magento cache:flush --all
```
